/**
 * @file timestamp_capture_regs.h
 * @brief Sub-nanosecond timestamp capture unit for QEDMMA TDOA processing
 *
 * Auto-generated from YAML - DO NOT EDIT MANUALLY
 * Generator: QEDMMA Forge v9.0
 * Generated: 2026-01-31 11:17:23
 * Version: 1.0.0
 */

#ifndef __TIMESTAMP_CAPTURE_REGS_H__
#define __TIMESTAMP_CAPTURE_REGS_H__

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Base address (set by platform) */
#ifndef TIMESTAMP_CAPTURE_BASE_ADDR
#define TIMESTAMP_CAPTURE_BASE_ADDR 0x80000000UL
#endif

/* Register Offsets */
#define TIMESTAMP_CAPTURE_CTRL_OFFSET 0x000U /* Main control register */
#define TIMESTAMP_CAPTURE_STATUS_OFFSET 0x004U /* Status register */
#define TIMESTAMP_CAPTURE_IRQ_EN_OFFSET 0x008U /* Interrupt enable register */
#define TIMESTAMP_CAPTURE_IRQ_STATUS_OFFSET 0x00CU /* Interrupt status register (write 1 to clear) */
#define TIMESTAMP_CAPTURE_TS_SEC_LO_OFFSET 0x100U /* Timestamp seconds counter [31:0] */
#define TIMESTAMP_CAPTURE_TS_SEC_HI_OFFSET 0x104U /* Timestamp seconds counter [47:32] */
#define TIMESTAMP_CAPTURE_TS_NS_OFFSET 0x108U /* Timestamp nanoseconds within second */
#define TIMESTAMP_CAPTURE_TS_FRAC_OFFSET 0x10CU /* Sub-nanosecond fractional timestamp (TDC) */
#define TIMESTAMP_CAPTURE_TS_LATCH_CTRL_OFFSET 0x110U /* Timestamp latch control */
#define TIMESTAMP_CAPTURE_CH0_CTRL_OFFSET 0x200U /* Channel 0 control */
#define TIMESTAMP_CAPTURE_CH0_TS_SEC_OFFSET 0x204U /* Channel 0 captured seconds (FIFO read) */
#define TIMESTAMP_CAPTURE_CH0_TS_NS_OFFSET 0x208U /* Channel 0 captured nanoseconds (FIFO read) */
#define TIMESTAMP_CAPTURE_CH0_TS_FRAC_OFFSET 0x20CU /* Channel 0 captured fractional ns (FIFO read) */
#define TIMESTAMP_CAPTURE_CH1_CTRL_OFFSET 0x210U /* Channel 1 control (same fields as CH0) */
#define TIMESTAMP_CAPTURE_CH1_TS_SEC_OFFSET 0x214U /*  */
#define TIMESTAMP_CAPTURE_CH1_TS_NS_OFFSET 0x218U /*  */
#define TIMESTAMP_CAPTURE_CH1_TS_FRAC_OFFSET 0x21CU /*  */
#define TIMESTAMP_CAPTURE_CH2_CTRL_OFFSET 0x220U /*  */
#define TIMESTAMP_CAPTURE_CH2_TS_SEC_OFFSET 0x224U /*  */
#define TIMESTAMP_CAPTURE_CH2_TS_NS_OFFSET 0x228U /*  */
#define TIMESTAMP_CAPTURE_CH2_TS_FRAC_OFFSET 0x22CU /*  */
#define TIMESTAMP_CAPTURE_CH3_CTRL_OFFSET 0x230U /*  */
#define TIMESTAMP_CAPTURE_CH3_TS_SEC_OFFSET 0x234U /*  */
#define TIMESTAMP_CAPTURE_CH3_TS_NS_OFFSET 0x238U /*  */
#define TIMESTAMP_CAPTURE_CH3_TS_FRAC_OFFSET 0x23CU /*  */
#define TIMESTAMP_CAPTURE_CAL_CTRL_OFFSET 0x300U /* Calibration control */
#define TIMESTAMP_CAPTURE_CAL_OFFSET_OFFSET 0x304U /* Calibration offset (signed, in TDC units) */
#define TIMESTAMP_CAPTURE_CAL_SKEW_OFFSET 0x308U /* Inter-channel skew calibration */
#define TIMESTAMP_CAPTURE_VERSION_OFFSET 0xF00U /* IP version register */
#define TIMESTAMP_CAPTURE_ID_OFFSET 0xF04U /* IP identification (ASCII 'QEDT') */
#define TIMESTAMP_CAPTURE_BUILD_DATE_OFFSET 0xF08U /* Build date (BCD: YYYYMMDD) */
#define TIMESTAMP_CAPTURE_GIT_HASH_OFFSET 0xF0CU /* Git commit hash (lower 32 bits) */

/* Register Addresses */
#define TIMESTAMP_CAPTURE_CTRL (TIMESTAMP_CAPTURE_BASE_ADDR + 0x000U)
#define TIMESTAMP_CAPTURE_STATUS (TIMESTAMP_CAPTURE_BASE_ADDR + 0x004U)
#define TIMESTAMP_CAPTURE_IRQ_EN (TIMESTAMP_CAPTURE_BASE_ADDR + 0x008U)
#define TIMESTAMP_CAPTURE_IRQ_STATUS (TIMESTAMP_CAPTURE_BASE_ADDR + 0x00CU)
#define TIMESTAMP_CAPTURE_TS_SEC_LO (TIMESTAMP_CAPTURE_BASE_ADDR + 0x100U)
#define TIMESTAMP_CAPTURE_TS_SEC_HI (TIMESTAMP_CAPTURE_BASE_ADDR + 0x104U)
#define TIMESTAMP_CAPTURE_TS_NS (TIMESTAMP_CAPTURE_BASE_ADDR + 0x108U)
#define TIMESTAMP_CAPTURE_TS_FRAC (TIMESTAMP_CAPTURE_BASE_ADDR + 0x10CU)
#define TIMESTAMP_CAPTURE_TS_LATCH_CTRL (TIMESTAMP_CAPTURE_BASE_ADDR + 0x110U)
#define TIMESTAMP_CAPTURE_CH0_CTRL (TIMESTAMP_CAPTURE_BASE_ADDR + 0x200U)
#define TIMESTAMP_CAPTURE_CH0_TS_SEC (TIMESTAMP_CAPTURE_BASE_ADDR + 0x204U)
#define TIMESTAMP_CAPTURE_CH0_TS_NS (TIMESTAMP_CAPTURE_BASE_ADDR + 0x208U)
#define TIMESTAMP_CAPTURE_CH0_TS_FRAC (TIMESTAMP_CAPTURE_BASE_ADDR + 0x20CU)
#define TIMESTAMP_CAPTURE_CH1_CTRL (TIMESTAMP_CAPTURE_BASE_ADDR + 0x210U)
#define TIMESTAMP_CAPTURE_CH1_TS_SEC (TIMESTAMP_CAPTURE_BASE_ADDR + 0x214U)
#define TIMESTAMP_CAPTURE_CH1_TS_NS (TIMESTAMP_CAPTURE_BASE_ADDR + 0x218U)
#define TIMESTAMP_CAPTURE_CH1_TS_FRAC (TIMESTAMP_CAPTURE_BASE_ADDR + 0x21CU)
#define TIMESTAMP_CAPTURE_CH2_CTRL (TIMESTAMP_CAPTURE_BASE_ADDR + 0x220U)
#define TIMESTAMP_CAPTURE_CH2_TS_SEC (TIMESTAMP_CAPTURE_BASE_ADDR + 0x224U)
#define TIMESTAMP_CAPTURE_CH2_TS_NS (TIMESTAMP_CAPTURE_BASE_ADDR + 0x228U)
#define TIMESTAMP_CAPTURE_CH2_TS_FRAC (TIMESTAMP_CAPTURE_BASE_ADDR + 0x22CU)
#define TIMESTAMP_CAPTURE_CH3_CTRL (TIMESTAMP_CAPTURE_BASE_ADDR + 0x230U)
#define TIMESTAMP_CAPTURE_CH3_TS_SEC (TIMESTAMP_CAPTURE_BASE_ADDR + 0x234U)
#define TIMESTAMP_CAPTURE_CH3_TS_NS (TIMESTAMP_CAPTURE_BASE_ADDR + 0x238U)
#define TIMESTAMP_CAPTURE_CH3_TS_FRAC (TIMESTAMP_CAPTURE_BASE_ADDR + 0x23CU)
#define TIMESTAMP_CAPTURE_CAL_CTRL (TIMESTAMP_CAPTURE_BASE_ADDR + 0x300U)
#define TIMESTAMP_CAPTURE_CAL_OFFSET (TIMESTAMP_CAPTURE_BASE_ADDR + 0x304U)
#define TIMESTAMP_CAPTURE_CAL_SKEW (TIMESTAMP_CAPTURE_BASE_ADDR + 0x308U)
#define TIMESTAMP_CAPTURE_VERSION (TIMESTAMP_CAPTURE_BASE_ADDR + 0xF00U)
#define TIMESTAMP_CAPTURE_ID (TIMESTAMP_CAPTURE_BASE_ADDR + 0xF04U)
#define TIMESTAMP_CAPTURE_BUILD_DATE (TIMESTAMP_CAPTURE_BASE_ADDR + 0xF08U)
#define TIMESTAMP_CAPTURE_GIT_HASH (TIMESTAMP_CAPTURE_BASE_ADDR + 0xF0CU)

/* Field Masks and Positions */
#define TIMESTAMP_CAPTURE_CTRL_ENABLE_BIT  0U
#define TIMESTAMP_CAPTURE_CTRL_ENABLE_MASK (1U << 0U)
#define TIMESTAMP_CAPTURE_CTRL_SYNC_SRC_BIT  121U
#define TIMESTAMP_CAPTURE_CTRL_SYNC_SRC_MASK (1U << 121U)
#define TIMESTAMP_CAPTURE_CTRL_ARM_MODE_BIT  243U
#define TIMESTAMP_CAPTURE_CTRL_ARM_MODE_MASK (1U << 243U)
#define TIMESTAMP_CAPTURE_CTRL_CH_EN_BIT  668U
#define TIMESTAMP_CAPTURE_CTRL_CH_EN_MASK (1U << 668U)
#define TIMESTAMP_CAPTURE_CTRL_FIFO_CLR_BIT  16U
#define TIMESTAMP_CAPTURE_CTRL_FIFO_CLR_MASK (1U << 16U)
#define TIMESTAMP_CAPTURE_CTRL_SOFT_TRIG_BIT  24U
#define TIMESTAMP_CAPTURE_CTRL_SOFT_TRIG_MASK (1U << 24U)
#define TIMESTAMP_CAPTURE_CTRL_SOFT_RST_BIT  31U
#define TIMESTAMP_CAPTURE_CTRL_SOFT_RST_MASK (1U << 31U)
#define TIMESTAMP_CAPTURE_STATUS_LOCKED_BIT  0U
#define TIMESTAMP_CAPTURE_STATUS_LOCKED_MASK (1U << 0U)
#define TIMESTAMP_CAPTURE_STATUS_HOLDOVER_BIT  1U
#define TIMESTAMP_CAPTURE_STATUS_HOLDOVER_MASK (1U << 1U)
#define TIMESTAMP_CAPTURE_STATUS_SYNC_SRC_ACT_BIT  182U
#define TIMESTAMP_CAPTURE_STATUS_SYNC_SRC_ACT_MASK (1U << 182U)
#define TIMESTAMP_CAPTURE_STATUS_FIFO_EMPTY_BIT  668U
#define TIMESTAMP_CAPTURE_STATUS_FIFO_EMPTY_MASK (1U << 668U)
#define TIMESTAMP_CAPTURE_STATUS_FIFO_FULL_BIT  912U
#define TIMESTAMP_CAPTURE_STATUS_FIFO_FULL_MASK (1U << 912U)
#define TIMESTAMP_CAPTURE_STATUS_FIFO_OVERFLOW_BIT  1156U
#define TIMESTAMP_CAPTURE_STATUS_FIFO_OVERFLOW_MASK (1U << 1156U)
#define TIMESTAMP_CAPTURE_STATUS_PPS_COUNT_BIT  1884U
#define TIMESTAMP_CAPTURE_STATUS_PPS_COUNT_MASK (1U << 1884U)
#define TIMESTAMP_CAPTURE_IRQ_EN_CAPTURE_EN_BIT  180U
#define TIMESTAMP_CAPTURE_IRQ_EN_CAPTURE_EN_MASK (1U << 180U)
#define TIMESTAMP_CAPTURE_IRQ_EN_FIFO_THRESH_EN_BIT  424U
#define TIMESTAMP_CAPTURE_IRQ_EN_FIFO_THRESH_EN_MASK (1U << 424U)
#define TIMESTAMP_CAPTURE_IRQ_EN_OVERFLOW_EN_BIT  668U
#define TIMESTAMP_CAPTURE_IRQ_EN_OVERFLOW_EN_MASK (1U << 668U)
#define TIMESTAMP_CAPTURE_IRQ_EN_PPS_EN_BIT  16U
#define TIMESTAMP_CAPTURE_IRQ_EN_PPS_EN_MASK (1U << 16U)
#define TIMESTAMP_CAPTURE_IRQ_EN_LOCK_CHANGE_EN_BIT  17U
#define TIMESTAMP_CAPTURE_IRQ_EN_LOCK_CHANGE_EN_MASK (1U << 17U)
#define TIMESTAMP_CAPTURE_IRQ_STATUS_CAPTURE_BIT  180U
#define TIMESTAMP_CAPTURE_IRQ_STATUS_CAPTURE_MASK (1U << 180U)
#define TIMESTAMP_CAPTURE_IRQ_STATUS_FIFO_THRESH_BIT  424U
#define TIMESTAMP_CAPTURE_IRQ_STATUS_FIFO_THRESH_MASK (1U << 424U)
#define TIMESTAMP_CAPTURE_IRQ_STATUS_OVERFLOW_BIT  668U
#define TIMESTAMP_CAPTURE_IRQ_STATUS_OVERFLOW_MASK (1U << 668U)
#define TIMESTAMP_CAPTURE_IRQ_STATUS_PPS_BIT  16U
#define TIMESTAMP_CAPTURE_IRQ_STATUS_PPS_MASK (1U << 16U)
#define TIMESTAMP_CAPTURE_IRQ_STATUS_LOCK_CHANGE_BIT  17U
#define TIMESTAMP_CAPTURE_IRQ_STATUS_LOCK_CHANGE_MASK (1U << 17U)
#define TIMESTAMP_CAPTURE_TS_SEC_LO_VALUE_BIT  1860U
#define TIMESTAMP_CAPTURE_TS_SEC_LO_VALUE_MASK (1U << 1860U)
#define TIMESTAMP_CAPTURE_TS_SEC_HI_VALUE_BIT  900U
#define TIMESTAMP_CAPTURE_TS_SEC_HI_VALUE_MASK (1U << 900U)
#define TIMESTAMP_CAPTURE_TS_SEC_HI_RESERVED_BIT  1876U
#define TIMESTAMP_CAPTURE_TS_SEC_HI_RESERVED_MASK (1U << 1876U)
#define TIMESTAMP_CAPTURE_TS_NS_VALUE_BIT  1740U
#define TIMESTAMP_CAPTURE_TS_NS_VALUE_MASK (1U << 1740U)
#define TIMESTAMP_CAPTURE_TS_NS_RESERVED_BIT  1890U
#define TIMESTAMP_CAPTURE_TS_NS_RESERVED_MASK (1U << 1890U)
#define TIMESTAMP_CAPTURE_TS_FRAC_VALUE_BIT  900U
#define TIMESTAMP_CAPTURE_TS_FRAC_VALUE_MASK (1U << 900U)
#define TIMESTAMP_CAPTURE_TS_FRAC_VALID_BIT  31U
#define TIMESTAMP_CAPTURE_TS_FRAC_VALID_MASK (1U << 31U)
#define TIMESTAMP_CAPTURE_TS_LATCH_CTRL_LATCH_BIT  0U
#define TIMESTAMP_CAPTURE_TS_LATCH_CTRL_LATCH_MASK (1U << 0U)
#define TIMESTAMP_CAPTURE_TS_LATCH_CTRL_AUTO_LATCH_BIT  1U
#define TIMESTAMP_CAPTURE_TS_LATCH_CTRL_AUTO_LATCH_MASK (1U << 1U)
#define TIMESTAMP_CAPTURE_CH0_CTRL_EDGE_SEL_BIT  0U
#define TIMESTAMP_CAPTURE_CH0_CTRL_EDGE_SEL_MASK (1U << 0U)
#define TIMESTAMP_CAPTURE_CH0_CTRL_FILTER_EN_BIT  1U
#define TIMESTAMP_CAPTURE_CH0_CTRL_FILTER_EN_MASK (1U << 1U)
#define TIMESTAMP_CAPTURE_CH0_CTRL_FILTER_LEN_BIT  424U
#define TIMESTAMP_CAPTURE_CH0_CTRL_FILTER_LEN_MASK (1U << 424U)
#define TIMESTAMP_CAPTURE_CH0_CTRL_FIFO_THRESH_BIT  908U
#define TIMESTAMP_CAPTURE_CH0_CTRL_FIFO_THRESH_MASK (1U << 908U)
#define TIMESTAMP_CAPTURE_CH0_TS_SEC_VALUE_BIT  1860U
#define TIMESTAMP_CAPTURE_CH0_TS_SEC_VALUE_MASK (1U << 1860U)
#define TIMESTAMP_CAPTURE_CH0_TS_NS_VALUE_BIT  1740U
#define TIMESTAMP_CAPTURE_CH0_TS_NS_VALUE_MASK (1U << 1740U)
#define TIMESTAMP_CAPTURE_CH0_TS_NS_RESERVED_BIT  1890U
#define TIMESTAMP_CAPTURE_CH0_TS_NS_RESERVED_MASK (1U << 1890U)
#define TIMESTAMP_CAPTURE_CH0_TS_FRAC_VALUE_BIT  900U
#define TIMESTAMP_CAPTURE_CH0_TS_FRAC_VALUE_MASK (1U << 900U)
#define TIMESTAMP_CAPTURE_CH0_TS_FRAC_FIFO_COUNT_BIT  1636U
#define TIMESTAMP_CAPTURE_CH0_TS_FRAC_FIFO_COUNT_MASK (1U << 1636U)
#define TIMESTAMP_CAPTURE_CH0_TS_FRAC_VALID_BIT  31U
#define TIMESTAMP_CAPTURE_CH0_TS_FRAC_VALID_MASK (1U << 31U)
#define TIMESTAMP_CAPTURE_CAL_CTRL_CAL_EN_BIT  0U
#define TIMESTAMP_CAPTURE_CAL_CTRL_CAL_EN_MASK (1U << 0U)
#define TIMESTAMP_CAPTURE_CAL_CTRL_CAL_SRC_BIT  121U
#define TIMESTAMP_CAPTURE_CAL_CTRL_CAL_SRC_MASK (1U << 121U)
#define TIMESTAMP_CAPTURE_CAL_CTRL_CAL_START_BIT  8U
#define TIMESTAMP_CAPTURE_CAL_CTRL_CAL_START_MASK (1U << 8U)
#define TIMESTAMP_CAPTURE_CAL_CTRL_CAL_BUSY_BIT  16U
#define TIMESTAMP_CAPTURE_CAL_CTRL_CAL_BUSY_MASK (1U << 16U)
#define TIMESTAMP_CAPTURE_CAL_CTRL_CAL_DONE_BIT  17U
#define TIMESTAMP_CAPTURE_CAL_CTRL_CAL_DONE_MASK (1U << 17U)
#define TIMESTAMP_CAPTURE_CAL_CTRL_CAL_ERROR_BIT  18U
#define TIMESTAMP_CAPTURE_CAL_CTRL_CAL_ERROR_MASK (1U << 18U)
#define TIMESTAMP_CAPTURE_CAL_OFFSET_VALUE_BIT  900U
#define TIMESTAMP_CAPTURE_CAL_OFFSET_VALUE_MASK (1U << 900U)
#define TIMESTAMP_CAPTURE_CAL_OFFSET_AUTO_APPLY_BIT  31U
#define TIMESTAMP_CAPTURE_CAL_OFFSET_AUTO_APPLY_MASK (1U << 31U)
#define TIMESTAMP_CAPTURE_CAL_SKEW_CH1_SKEW_BIT  420U
#define TIMESTAMP_CAPTURE_CAL_SKEW_CH1_SKEW_MASK (1U << 420U)
#define TIMESTAMP_CAPTURE_CAL_SKEW_CH2_SKEW_BIT  908U
#define TIMESTAMP_CAPTURE_CAL_SKEW_CH2_SKEW_MASK (1U << 908U)
#define TIMESTAMP_CAPTURE_CAL_SKEW_CH3_SKEW_BIT  1396U
#define TIMESTAMP_CAPTURE_CAL_SKEW_CH3_SKEW_MASK (1U << 1396U)
#define TIMESTAMP_CAPTURE_VERSION_PATCH_BIT  420U
#define TIMESTAMP_CAPTURE_VERSION_PATCH_MASK (1U << 420U)
#define TIMESTAMP_CAPTURE_VERSION_MINOR_BIT  908U
#define TIMESTAMP_CAPTURE_VERSION_MINOR_MASK (1U << 908U)
#define TIMESTAMP_CAPTURE_VERSION_MAJOR_BIT  1396U
#define TIMESTAMP_CAPTURE_VERSION_MAJOR_MASK (1U << 1396U)
#define TIMESTAMP_CAPTURE_VERSION_RESERVED_BIT  1884U
#define TIMESTAMP_CAPTURE_VERSION_RESERVED_MASK (1U << 1884U)
#define TIMESTAMP_CAPTURE_ID_VALUE_BIT  1860U
#define TIMESTAMP_CAPTURE_ID_VALUE_MASK (1U << 1860U)
#define TIMESTAMP_CAPTURE_BUILD_DATE_VALUE_BIT  1860U
#define TIMESTAMP_CAPTURE_BUILD_DATE_VALUE_MASK (1U << 1860U)
#define TIMESTAMP_CAPTURE_GIT_HASH_VALUE_BIT  1860U
#define TIMESTAMP_CAPTURE_GIT_HASH_VALUE_MASK (1U << 1860U)

/* Helper Macros */
#define TIMESTAMP_CAPTURE_READ(reg) (*(volatile uint32_t*)(reg))
#define TIMESTAMP_CAPTURE_WRITE(reg, val) (*(volatile uint32_t*)(reg) = (val))
#define TIMESTAMP_CAPTURE_SET_BITS(reg, mask) TIMESTAMP_CAPTURE_WRITE(reg, TIMESTAMP_CAPTURE_READ(reg) | (mask))
#define TIMESTAMP_CAPTURE_CLR_BITS(reg, mask) TIMESTAMP_CAPTURE_WRITE(reg, TIMESTAMP_CAPTURE_READ(reg) & ~(mask))

#ifdef __cplusplus
}
#endif

#endif /* __TIMESTAMP_CAPTURE_REGS_H__ */