#!/usr/bin/env python3
"""
QEDMMA BOM Generator v1.3
=========================
Generates comprehensive Bill of Materials spreadsheet with:
- Detailed component breakdown per subsystem
- Primary and alternative suppliers
- Volume pricing tiers
- EOL risk assessment
- Lead time tracking

Auto-generated by Radar Systems Architect v9.0 - Cost & Supply Lead
Date: 2026-01-31
"""

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.formatting.rule import ColorScaleRule, FormulaRule
from openpyxl.chart import BarChart, PieChart, Reference
from openpyxl.chart.label import DataLabelList
import os

# Create workbook
wb = Workbook()

# Color definitions
HEADER_FILL = PatternFill("solid", fgColor="1F4E79")
HEADER_FONT = Font(bold=True, color="FFFFFF", size=11)
SUBHEADER_FILL = PatternFill("solid", fgColor="2E75B6")
CATEGORY_FILL = PatternFill("solid", fgColor="BDD7EE")
CATEGORY_FONT = Font(bold=True, size=10)
TOTAL_FILL = PatternFill("solid", fgColor="FFC000")
TOTAL_FONT = Font(bold=True, size=11)
WARNING_FILL = PatternFill("solid", fgColor="FF6B6B")
CAUTION_FILL = PatternFill("solid", fgColor="FFE066")
OK_FILL = PatternFill("solid", fgColor="69DB7C")
THIN_BORDER = Border(
    left=Side(style='thin'),
    right=Side(style='thin'),
    top=Side(style='thin'),
    bottom=Side(style='thin')
)

def style_header_row(sheet, row, start_col=1, end_col=15):
    for col in range(start_col, end_col + 1):
        cell = sheet.cell(row=row, column=col)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
        cell.border = THIN_BORDER

def style_category_row(sheet, row, start_col=1, end_col=15):
    for col in range(start_col, end_col + 1):
        cell = sheet.cell(row=row, column=col)
        cell.fill = CATEGORY_FILL
        cell.font = CATEGORY_FONT
        cell.border = THIN_BORDER

def style_total_row(sheet, row, start_col=1, end_col=15):
    for col in range(start_col, end_col + 1):
        cell = sheet.cell(row=row, column=col)
        cell.fill = TOTAL_FILL
        cell.font = TOTAL_FONT
        cell.border = THIN_BORDER

def apply_borders(sheet, start_row, end_row, start_col, end_col):
    for row in range(start_row, end_row + 1):
        for col in range(start_col, end_col + 1):
            sheet.cell(row=row, column=col).border = THIN_BORDER

# =============================================================================
# SHEET 1: Executive Summary
# =============================================================================
ws_summary = wb.active
ws_summary.title = "Executive Summary"

# Title
ws_summary['A1'] = "QEDMMA BOM & Cost Analysis v1.3"
ws_summary['A1'].font = Font(bold=True, size=16, color="1F4E79")
ws_summary.merge_cells('A1:H1')

ws_summary['A2'] = "Quantum-Enhanced Distributed Metamaterial Multistatic Array"
ws_summary['A2'].font = Font(italic=True, size=12)
ws_summary.merge_cells('A2:H2')

ws_summary['A3'] = "Generated: 31-Jan-2026 | Radar Systems Architect v9.0"
ws_summary['A3'].font = Font(size=10, color="666666")

# Summary table
summary_headers = ['Subsystem', 'Qty (MVP)', 'Unit Cost (€)', 'Total (€)', 'Serial Cost (€)', 'Notes']
for col, header in enumerate(summary_headers, 1):
    ws_summary.cell(row=5, column=col, value=header)
style_header_row(ws_summary, 5, 1, 6)

summary_data = [
    ['Rx Node (Quantum Receiver)', 4, 165000, '=B6*C6', 52000, 'Rydberg sensor + FPGA + timing'],
    ['Tx Node (Illuminator)', 1, 85000, '=B7*C7', 35000, 'GaN PA + waveform generator'],
    ['C2 Fusion Center', 1, 120000, '=B8*C8', 75000, 'GPU servers + software'],
    ['Infrastructure & Cabling', 1, 45000, '=B9*C9', 25000, 'White Rabbit network, power'],
    ['Integration & Test', 1, 80000, '=B10*C10', 30000, 'System integration, calibration'],
    ['Contingency (15%)', 1, '=SUM(D6:D10)*0.15', '=B11*C11', '=SUM(E6:E10)*0.15', 'Risk buffer'],
]

for row_idx, row_data in enumerate(summary_data, 6):
    for col_idx, value in enumerate(row_data, 1):
        ws_summary.cell(row=row_idx, column=col_idx, value=value)
    apply_borders(ws_summary, row_idx, row_idx, 1, 6)

# Totals
ws_summary.cell(row=12, column=1, value="TOTAL MVP COST")
ws_summary.cell(row=12, column=4, value='=SUM(D6:D11)')
ws_summary.cell(row=12, column=5, value='=SUM(E6:E11)')
ws_summary.cell(row=12, column=6, value='4 Rx + 1 Tx + C2')
style_total_row(ws_summary, 12, 1, 6)

# Key metrics
ws_summary['A15'] = "KEY METRICS"
ws_summary['A15'].font = Font(bold=True, size=12)

metrics = [
    ['Metric', 'Value', 'Target', 'Status'],
    ['Prototype Cost per Rx Node', '€165,000', '€150,000', 'YELLOW'],
    ['Serial Cost per Rx Node (100+)', '€52,000', '€50,000', 'GREEN'],
    ['MVP Total Budget', '=D12', '€750,000', '=IF(D12<750000,"GREEN","YELLOW")'],
    ['BOM Confidence Level', '±12%', '±10%', 'YELLOW'],
    ['Lead Time (Critical Path)', '16-20 weeks', '<12 weeks', 'RED'],
]

for row_idx, row_data in enumerate(metrics, 16):
    for col_idx, value in enumerate(row_data, 1):
        cell = ws_summary.cell(row=row_idx, column=col_idx, value=value)
        if row_idx == 16:
            cell.fill = HEADER_FILL
            cell.font = HEADER_FONT
        elif col_idx == 4:
            if value == 'GREEN':
                cell.fill = OK_FILL
            elif value == 'YELLOW':
                cell.fill = CAUTION_FILL
            elif value == 'RED':
                cell.fill = WARNING_FILL
        cell.border = THIN_BORDER

# Column widths
ws_summary.column_dimensions['A'].width = 30
ws_summary.column_dimensions['B'].width = 15
ws_summary.column_dimensions['C'].width = 18
ws_summary.column_dimensions['D'].width = 15
ws_summary.column_dimensions['E'].width = 18
ws_summary.column_dimensions['F'].width = 35

# =============================================================================
# SHEET 2: Rx Node BOM (Detailed)
# =============================================================================
ws_rx = wb.create_sheet("Rx Node BOM")

ws_rx['A1'] = "QEDMMA Rx Node - Detailed Bill of Materials"
ws_rx['A1'].font = Font(bold=True, size=14, color="1F4E79")
ws_rx.merge_cells('A1:L1')

headers = [
    'Category', 'Part Number', 'Description', 'Manufacturer', 
    'Qty', 'Unit (€)', 'Extended (€)', 'Lead Time', 
    'EOL Risk', 'Alternative', 'Alt Cost (€)', 'Notes'
]

for col, header in enumerate(headers, 1):
    ws_rx.cell(row=3, column=col, value=header)
style_header_row(ws_rx, 3, 1, 12)

# Detailed BOM data
rx_bom = [
    # Rydberg Quantum Sensor Subsystem
    ['RYDBERG SENSOR SUBSYSTEM', '', '', '', '', '', '=SUMIF(A:A,A5,G:G)', '', '', '', '', ''],
    ['Rydberg Sensor', 'DL-PRO-780', '780nm Probe Laser (ECDL)', 'Toptica', 1, 28000, '=E6*F6', '12-16 wks', 'LOW', 'Moglabs CEL002', 25000, 'EIT probe, ±0.1pm stability'],
    ['Rydberg Sensor', 'OBIS-480-100', '480nm Coupling Laser', 'Coherent', 1, 18000, '=E7*F7', '8-12 wks', 'LOW', 'Toptica DL100', 22000, 'Rydberg excitation'],
    ['Rydberg Sensor', 'QED-VC-85', 'Rb-85 Vapor Cell (custom)', 'Precision Glassblowing', 1, 8500, '=E8*F8', '8-10 wks', 'MED', 'Thorlabs GC25075-RB', 4500, '25mm path, AR coated'],
    ['Rydberg Sensor', 'QED-EIT-OPT', 'EIT Optics Assembly', 'Custom/Thorlabs', 1, 6500, '=E9*F9', '4-6 wks', 'LOW', '-', '-', 'PBS, waveplates, mounts'],
    ['Rydberg Sensor', 'APD430A2', 'Si APD Photodetector', 'Thorlabs', 2, 2800, '=E10*F10', '2-4 wks', 'LOW', 'Hamamatsu C12702', 2500, 'High-speed detection'],
    ['Rydberg Sensor', 'TEC-CTRL-01', 'TEC Controller + Cooling', 'Wavelength Electronics', 1, 3500, '=E11*F11', '4-6 wks', 'LOW', 'Thorlabs TED200C', 2800, 'Vapor cell temp stabilization'],
    ['Rydberg Sensor', 'QED-LCK-01', 'Laser Locking Electronics', 'Custom PCB', 1, 4500, '=E12*F12', '6-8 wks', 'MED', '-', '-', 'PDH lock, modulation'],
    
    # Metamaterial Antenna
    ['METAMATERIAL ANTENNA', '', '', '', '', '', '=SUMIF(A:A,A14,G:G)', '', '', '', '', ''],
    ['Antenna', 'QED-MMA-1M', '1m×1m Metamaterial Array', 'Custom/Metamagnetics', 1, 18000, '=E15*F15', '12-16 wks', 'HIGH', 'Fractal Antenna FA-VHF', 8000, 'VHF optimized, 10dBi gain equiv'],
    ['Antenna', 'LNA-VHF-01', 'VHF Low Noise Amplifier', 'Mini-Circuits ZKL-1R5+', 2, 450, '=E16*F16', '2-3 wks', 'LOW', 'Qorvo QPL9503', 380, 'NF<1.5dB, Gain 20dB'],
    ['Antenna', 'FILT-BP-150', 'Bandpass Filter 100-200MHz', 'K&L Microwave', 2, 850, '=E17*F17', '4-6 wks', 'LOW', 'Mini-Circuits VBFZ-150+', 420, 'Interference rejection'],
    ['Antenna', 'BIAS-TEE-01', 'Bias Tee + Protection', 'Mini-Circuits ZFBT-6GW+', 2, 180, '=E18*F18', '1-2 wks', 'LOW', '-', '-', 'LNA power injection'],
    
    # FPGA & Signal Processing
    ['FPGA & PROCESSING', '', '', '', '', '', '=SUMIF(A:A,A20,G:G)', '', '', '', '', ''],
    ['FPGA', 'XCZU47DR-2FFVG1517E', 'Zynq RFSoC (ZU47DR)', 'AMD/Xilinx', 1, 12500, '=E21*F21', '16-24 wks', 'MED', 'XCZU39DR (lower spec)', 8500, 'CRITICAL - long lead'],
    ['FPGA', 'ZCU216-EVAL', 'RFSoC Eval Board', 'AMD/Xilinx', 1, 8500, '=E22*F22', '4-8 wks', 'LOW', 'HTG-ZRF16 (HiTech Global)', 9200, 'For rapid prototype'],
    ['FPGA', 'DDR4-16G-ECC', '16GB DDR4 ECC SODIMM', 'Micron MTA18ASF2G72HZ', 2, 180, '=E23*F23', '2-4 wks', 'LOW', 'Samsung M474A2K43', 165, 'Frame buffer, FFT'],
    ['FPGA', 'NVME-2TB', '2TB NVMe SSD', 'Samsung 990 Pro', 1, 220, '=E24*F24', '1-2 wks', 'LOW', 'WD Black SN850X', 200, 'Raw data logging'],
    
    # Edge AI Processing
    ['EDGE AI', '', '', '', '', '', '=SUMIF(A:A,A26,G:G)', '', '', '', '', ''],
    ['AI', 'ORIN-AGX-64', 'NVIDIA Jetson Orin AGX 64GB', 'NVIDIA', 1, 2200, '=E27*F27', '8-12 wks', 'LOW', 'Orin NX 16GB', 1100, 'AI inference, tracking'],
    ['AI', 'CARRIER-ORIN', 'Orin Carrier Board (rugged)', 'Connect Tech Forge', 1, 850, '=E28*F28', '4-6 wks', 'LOW', 'Seeed reComputer', 450, 'MIL-temp range'],
    
    # Timing Subsystem
    ['TIMING SUBSYSTEM', '', '', '', '', '', '=SUMIF(A:A,A30,G:G)', '', '', '', '', ''],
    ['Timing', 'SA.45s', 'CSAC (Chip-Scale Atomic Clock)', 'Microchip', 1, 4200, '=E31*F31', '12-16 wks', 'MED', 'Oscilloquartz OSA 3235B', 5800, 'Holdover: 3e-10 drift'],
    ['Timing', 'MAC-SA.35m', 'Rb Atomic Clock (upgrade)', 'Microchip', 0, 8500, '=E32*F32', '12-16 wks', 'MED', 'Stanford PRS10', 7500, 'OPTIONAL: 10x better holdover'],
    ['Timing', 'WR-LEN', 'White Rabbit LEN (slave)', 'Seven Solutions', 1, 4500, '=E33*F33', '6-8 wks', 'LOW', 'CERN WR-Lite', 3200, '<1ns network sync'],
    ['Timing', 'SFP-1G-WR', 'WR SFP Module', 'Seven Solutions', 2, 280, '=E34*F34', '2-4 wks', 'LOW', '-', '-', 'Fiber optic link'],
    ['Timing', 'GPS-DISC', 'GPS Disciplined Reference', 'Trimble Resolution T', 1, 1800, '=E35*F35', '4-6 wks', 'LOW', 'u-blox ZED-F9T', 450, 'Backup timing source'],
    
    # Power & Enclosure
    ['POWER & ENCLOSURE', '', '', '', '', '', '=SUMIF(A:A,A37,G:G)', '', '', '', '', ''],
    ['Power', 'PSU-1500W-MIL', '1500W Mil-Spec PSU', 'Vicor MIL-COTS', 1, 2800, '=E38*F38', '8-12 wks', 'LOW', 'Mean Well RSP-1600', 450, 'MIL-STD-461 EMI'],
    ['Power', 'UPS-RACK-3KVA', 'Rack UPS 3kVA', 'APC Smart-UPS', 1, 2200, '=E39*F39', '2-4 wks', 'LOW', 'Eaton 5PX3000', 1950, '15min holdover'],
    ['Power', 'PDU-SMART', 'Smart PDU (monitored)', 'Raritan PX3', 1, 850, '=E40*F40', '2-3 wks', 'LOW', 'APC AP8681', 720, 'Remote monitoring'],
    ['Enclosure', 'RACK-4U-MIL', '4U Rugged Transit Case', 'Pelican-Hardigg', 1, 4500, '=E41*F41', '4-6 wks', 'LOW', 'SKB 3RR-4U24-25B', 2800, 'MIL-STD-810H, IP67'],
    ['Enclosure', 'THERMAL-MGMT', 'Thermal Management Kit', 'Custom', 1, 3500, '=E42*F42', '6-8 wks', 'MED', '-', '-', 'Heat exchanger, fans'],
    ['Enclosure', 'CONN-MIL-KIT', 'MIL-Spec Connectors', 'Amphenol/TE', 1, 1200, '=E43*F43', '4-6 wks', 'LOW', '-', '-', 'D38999, SMA, fiber'],
    
    # Integration & Software
    ['INTEGRATION', '', '', '', '', '', '=SUMIF(A:A,A45,G:G)', '', '', '', '', ''],
    ['Integration', 'INT-HARNESS', 'Internal Wiring Harness', 'Custom', 1, 2500, '=E46*F46', '4-6 wks', 'LOW', '-', '-', 'Shielded, labeled'],
    ['Integration', 'INT-ASSEMBLY', 'Mechanical Assembly', 'Custom', 1, 5000, '=E47*F47', '6-8 wks', 'LOW', '-', '-', 'Vibration mounts, rails'],
    ['Integration', 'INT-CALIB', 'Factory Calibration', 'In-house', 1, 8000, '=E48*F48', '2-3 wks', '-', '-', '-', 'Full system test'],
]

row = 5
for item in rx_bom:
    for col, value in enumerate(item, 1):
        ws_rx.cell(row=row, column=col, value=value)
    # Style category rows
    if item[1] == '' and item[0] != '':
        style_category_row(ws_rx, row, 1, 12)
    apply_borders(ws_rx, row, row, 1, 12)
    row += 1

# Total row
ws_rx.cell(row=row, column=1, value="TOTAL Rx NODE")
ws_rx.cell(row=row, column=7, value='=SUM(G5:G48)')
style_total_row(ws_rx, row, 1, 12)

# Column widths
col_widths = [25, 22, 30, 20, 6, 12, 12, 12, 10, 20, 12, 30]
for i, width in enumerate(col_widths, 1):
    ws_rx.column_dimensions[get_column_letter(i)].width = width

# =============================================================================
# SHEET 3: Tx Node BOM
# =============================================================================
ws_tx = wb.create_sheet("Tx Node BOM")

ws_tx['A1'] = "QEDMMA Tx Node (Illuminator) - Bill of Materials"
ws_tx['A1'].font = Font(bold=True, size=14, color="1F4E79")
ws_tx.merge_cells('A1:L1')

for col, header in enumerate(headers, 1):
    ws_tx.cell(row=3, column=col, value=header)
style_header_row(ws_tx, 3, 1, 12)

tx_bom = [
    ['RF TRANSMITTER', '', '', '', '', '', '=SUMIF(A:A,A5,G:G)', '', '', '', '', ''],
    ['Transmitter', 'GaN-PA-10KW', 'GaN Solid-State PA 10kW', 'MACOM/Wolfspeed', 1, 28000, '=E6*F6', '16-20 wks', 'MED', 'Ampleon BLF578', 24000, 'VHF band, pulsed'],
    ['Transmitter', 'DRV-AMP-100W', 'Driver Amplifier 100W', 'Mini-Circuits ZHL-100W-GAN+', 1, 4500, '=E7*F7', '6-8 wks', 'LOW', '-', '-', 'Pre-driver stage'],
    ['Transmitter', 'FILT-LPF-200', 'Output LPF 200MHz', 'K&L Microwave', 1, 1200, '=E8*F8', '4-6 wks', 'LOW', '-', '-', 'Harmonic suppression'],
    ['Transmitter', 'CIRC-VHF', 'VHF Circulator 10kW', 'DiTom Microwave', 1, 3500, '=E9*F9', '8-10 wks', 'MED', '-', '-', 'PA protection'],
    ['Transmitter', 'DUMMYLOAD-10K', '10kW Dummy Load', 'Bird Technologies', 1, 2200, '=E10*F10', '4-6 wks', 'LOW', '-', '-', 'Testing/protection'],
    
    ['WAVEFORM GENERATOR', '', '', '', '', '', '=SUMIF(A:A,A12,G:G)', '', '', '', '', ''],
    ['Waveform', 'AD9361', 'RF Transceiver (2×2 MIMO)', 'Analog Devices', 1, 180, '=E13*F13', '12-16 wks', 'LOW', 'AD9364 (1×1)', 120, 'Baseband generation'],
    ['Waveform', 'FMCOMMS5', 'AD9361 Eval Platform', 'Analog Devices', 1, 2800, '=E14*F14', '4-6 wks', 'LOW', '-', '-', 'Rapid development'],
    ['Waveform', 'ZYNQ-ZC706', 'Zynq-7000 Dev Board', 'AMD/Xilinx', 1, 2500, '=E15*F15', '4-6 wks', 'LOW', 'ZedBoard', 650, 'Waveform generation'],
    ['Waveform', 'DAC-16BIT', 'DAC34SH84 Quad 16-bit DAC', 'Texas Instruments', 1, 450, '=E16*F16', '8-12 wks', 'LOW', 'AD9154', 380, 'High-speed DAC'],
    
    ['ANTENNA & FEED', '', '', '', '', '', '=SUMIF(A:A,A18,G:G)', '', '', '', '', ''],
    ['Antenna', 'ANT-LPDA-VHF', 'Log-Periodic Dipole Array', 'Schwarzbeck USLP 9143', 1, 4500, '=E19*F19', '6-8 wks', 'LOW', 'ETS-Lindgren 3148B', 5200, '80-1000MHz, 10dBi'],
    ['Antenna', 'ROTATOR-AZ', 'Antenna Azimuth Rotator', 'Yaesu G-2800DXA', 1, 1800, '=E20*F20', '4-6 wks', 'LOW', 'Kenpro KR-2000', 1400, 'Remote azimuth control'],
    ['Antenna', 'MAST-PNEU', 'Pneumatic Mast 12m', 'Will-Burt Night Scan', 1, 8500, '=E21*F21', '8-12 wks', 'LOW', 'Clark QMAC 40', 6500, 'Rapid deployment'],
    ['Antenna', 'COAX-7/8', '7/8" Low-Loss Coax 30m', 'Andrew LDF5-50A', 30, 45, '=E22*F22', '2-3 wks', 'LOW', 'RFS CELLFLEX', 42, 'Tx feedline'],
    
    ['CONTROL & TIMING', '', '', '', '', '', '=SUMIF(A:A,A24,G:G)', '', '', '', '', ''],
    ['Control', 'WR-SWITCH', 'White Rabbit Switch 18-port', 'Seven Solutions', 1, 5500, '=E25*F25', '6-8 wks', 'LOW', '-', '-', 'Timing distribution'],
    ['Control', 'OCXO-100M', 'OCXO 100MHz (±1ppb)', 'Oscilloquartz 8607', 1, 2800, '=E26*F26', '8-10 wks', 'LOW', 'Morion MV89A', 2200, 'Local reference'],
    ['Control', 'PXI-CHASSIS', 'PXI Chassis + Controller', 'National Instruments', 1, 6500, '=E27*F27', '4-6 wks', 'LOW', '-', '-', 'System control'],
    
    ['POWER & COOLING', '', '', '', '', '', '=SUMIF(A:A,A29,G:G)', '', '', '', '', ''],
    ['Power', 'PSU-PA-15KW', '15kW PA Power Supply', 'TDK-Lambda GEN600-25', 2, 4500, '=E30*F30', '8-12 wks', 'LOW', '-', '-', 'PA bias supply'],
    ['Power', 'COOLING-LIQUID', 'Liquid Cooling System', 'Asetek 690LX-PN', 1, 3500, '=E31*F31', '6-8 wks', 'LOW', '-', '-', 'PA thermal management'],
    ['Power', 'GEN-DIESEL-30', '30kVA Diesel Generator', 'Cummins C30D6', 1, 12000, '=E32*F32', '8-12 wks', 'LOW', 'Caterpillar DE33', 11500, 'Field deployment'],
    
    ['ENCLOSURE', '', '', '', '', '', '=SUMIF(A:A,A34,G:G)', '', '', '', '', ''],
    ['Enclosure', 'CONTAINER-10', '10ft ISO Container (modified)', 'Custom', 1, 8500, '=E35*F35', '10-14 wks', 'LOW', '-', '-', 'Mobile Tx shelter'],
    ['Enclosure', 'HVAC-UNIT', 'HVAC Unit 5kW', 'Bard Manufacturing', 1, 4500, '=E36*F36', '6-8 wks', 'LOW', '-', '-', 'Climate control'],
]

row = 5
for item in tx_bom:
    for col, value in enumerate(item, 1):
        ws_tx.cell(row=row, column=col, value=value)
    if item[1] == '' and item[0] != '':
        style_category_row(ws_tx, row, 1, 12)
    apply_borders(ws_tx, row, row, 1, 12)
    row += 1

ws_tx.cell(row=row, column=1, value="TOTAL Tx NODE")
ws_tx.cell(row=row, column=7, value='=SUM(G5:G36)')
style_total_row(ws_tx, row, 1, 12)

for i, width in enumerate(col_widths, 1):
    ws_tx.column_dimensions[get_column_letter(i)].width = width

# =============================================================================
# SHEET 4: C2 Fusion Center
# =============================================================================
ws_c2 = wb.create_sheet("C2 Fusion BOM")

ws_c2['A1'] = "QEDMMA C2 Fusion Center - Bill of Materials"
ws_c2['A1'].font = Font(bold=True, size=14, color="1F4E79")
ws_c2.merge_cells('A1:L1')

for col, header in enumerate(headers, 1):
    ws_c2.cell(row=3, column=col, value=header)
style_header_row(ws_c2, 3, 1, 12)

c2_bom = [
    ['COMPUTE SERVERS', '', '', '', '', '', '=SUMIF(A:A,A5,G:G)', '', '', '', '', ''],
    ['Server', 'GPU-SRV-A100', 'GPU Server (4× A100 80GB)', 'Dell PowerEdge R750xa', 1, 65000, '=E6*F6', '8-12 wks', 'LOW', 'Supermicro A+ 4124', 58000, 'Fusion processing'],
    ['Server', 'CPU-SRV-XEON', 'CPU Server (2× Xeon Gold)', 'Dell PowerEdge R650', 1, 12000, '=E7*F7', '4-6 wks', 'LOW', 'HPE DL360 Gen10', 11500, 'Data management'],
    ['Server', 'NAS-100TB', '100TB NAS Storage', 'Synology RS4021xs+', 1, 18000, '=E8*F8', '4-6 wks', 'LOW', 'QNAP TS-h3087XU', 16000, 'Data archival'],
    
    ['NETWORKING', '', '', '', '', '', '=SUMIF(A:A,A10,G:G)', '', '', '', '', ''],
    ['Network', 'SWITCH-25G', '25GbE Switch 48-port', 'Mellanox SN2700', 1, 8500, '=E11*F11', '4-6 wks', 'LOW', 'Arista 7050SX3', 9200, 'Data plane'],
    ['Network', 'WR-GM', 'White Rabbit Grandmaster', 'Seven Solutions', 1, 12000, '=E12*F12', '8-10 wks', 'MED', '-', '-', 'System timing master'],
    ['Network', 'ROUTER-EDGE', 'Edge Router (SATCOM ready)', 'Cisco ISR 4451', 1, 6500, '=E13*F13', '4-6 wks', 'LOW', 'Juniper SRX380', 5800, 'WAN connectivity'],
    
    ['DISPLAYS & HMI', '', '', '', '', '', '=SUMIF(A:A,A15,G:G)', '', '', '', '', ''],
    ['Display', 'DISPLAY-55-4K', '55" 4K Display', 'LG 55UN7300', 2, 650, '=E16*F16', '1-2 wks', 'LOW', '-', '-', 'Tactical display'],
    ['Display', 'CONSOLE-OP', 'Operator Console', 'Custom ergonomic', 2, 3500, '=E17*F17', '6-8 wks', 'LOW', '-', '-', 'Dual monitor, rack mount'],
    ['Display', 'KVM-SWITCH', 'KVM Switch 8-port', 'Raritan Dominion', 1, 2200, '=E18*F18', '2-4 wks', 'LOW', 'ATEN KN4140VA', 1800, 'Multi-server access'],
    
    ['SOFTWARE & LICENSES', '', '', '', '', '', '=SUMIF(A:A,A20,G:G)', '', '', '', '', ''],
    ['Software', 'SW-MATLAB', 'MATLAB + Toolboxes', 'MathWorks', 1, 8500, '=E21*F21', '1 wk', '-', '-', '-', 'Algorithm development'],
    ['Software', 'SW-CUDA', 'CUDA + cuDNN licenses', 'NVIDIA', 1, 0, '=E22*F22', '-', '-', '-', '-', 'Included with GPU'],
    ['Software', 'SW-CUSTOM', 'Custom Fusion Software', 'In-house development', 1, 0, '=E23*F23', '-', '-', '-', '-', 'Separate dev budget'],
]

row = 5
for item in c2_bom:
    for col, value in enumerate(item, 1):
        ws_c2.cell(row=row, column=col, value=value)
    if item[1] == '' and item[0] != '':
        style_category_row(ws_c2, row, 1, 12)
    apply_borders(ws_c2, row, row, 1, 12)
    row += 1

ws_c2.cell(row=row, column=1, value="TOTAL C2 CENTER")
ws_c2.cell(row=row, column=7, value='=SUM(G5:G23)')
style_total_row(ws_c2, row, 1, 12)

for i, width in enumerate(col_widths, 1):
    ws_c2.column_dimensions[get_column_letter(i)].width = width

# =============================================================================
# SHEET 5: Volume Pricing
# =============================================================================
ws_vol = wb.create_sheet("Volume Pricing")

ws_vol['A1'] = "QEDMMA Volume Pricing Analysis"
ws_vol['A1'].font = Font(bold=True, size=14, color="1F4E79")
ws_vol.merge_cells('A1:H1')

vol_headers = ['Component Category', 'Proto (1)', '10 units', '50 units', '100 units', 'Discount %', 'Notes']
for col, header in enumerate(vol_headers, 1):
    ws_vol.cell(row=3, column=col, value=header)
style_header_row(ws_vol, 3, 1, 7)

vol_data = [
    ['Rydberg Sensor Kit', 72000, 65000, 55000, 48000, '=1-F5/B5', 'Volume partnership pricing'],
    ['FPGA (ZU47DR)', 12500, 10500, 8500, 7200, '=1-F6/B6', 'AMD volume program'],
    ['Metamaterial Array', 18000, 14000, 10000, 7500, '=1-F7/B7', 'Tooling amortization'],
    ['Timing (CSAC+WR)', 8700, 7800, 6800, 5900, '=1-F8/B8', 'Modest volume savings'],
    ['NVIDIA Orin', 3050, 2700, 2300, 1950, '=1-F9/B9', 'NVIDIA partner pricing'],
    ['Power/Enclosure', 14050, 11500, 9000, 7200, '=1-F10/B10', 'Standard commodity scaling'],
    ['Integration/Calibration', 15500, 12000, 8000, 5500, '=1-F11/B11', 'Learning curve reduction'],
    ['SUBTOTAL Rx Node', '=SUM(B5:B11)', '=SUM(C5:C11)', '=SUM(D5:D11)', '=SUM(E5:E11)', '=1-F12/B12', ''],
    ['', '', '', '', '', '', ''],
    ['Tx Node', 85000, 72000, 58000, 48000, '=1-F14/B14', 'PA scaling, antenna tooling'],
    ['C2 Center (amortized)', 120000, 60000, 30000, 18000, '=1-F15/B15', 'Fixed cost spread'],
]

row = 5
for item in vol_data:
    for col, value in enumerate(item, 1):
        cell = ws_vol.cell(row=row, column=col, value=value)
        if col == 6 and isinstance(value, str) and value.startswith('='):
            cell.number_format = '0%'
    if row == 12:
        style_total_row(ws_vol, row, 1, 7)
    apply_borders(ws_vol, row, row, 1, 7)
    row += 1

# System totals
ws_vol.cell(row=18, column=1, value="SYSTEM COST (4 Rx + 1 Tx + C2)")
for col in range(2, 6):
    ws_vol.cell(row=18, column=col, value=f'=4*{get_column_letter(col)}12+{get_column_letter(col)}14+{get_column_letter(col)}15')
style_total_row(ws_vol, 18, 1, 7)

ws_vol.column_dimensions['A'].width = 25
for col in range(2, 8):
    ws_vol.column_dimensions[get_column_letter(col)].width = 12

# =============================================================================
# SHEET 6: Risk Assessment
# =============================================================================
ws_risk = wb.create_sheet("Risk Assessment")

ws_risk['A1'] = "QEDMMA Supply Chain Risk Assessment"
ws_risk['A1'].font = Font(bold=True, size=14, color="1F4E79")
ws_risk.merge_cells('A1:I1')

risk_headers = ['Component', 'EOL Risk', 'Single Source?', 'Lead Time', 'Geo Risk', 'Overall Risk', 'Mitigation Strategy', 'Alt Available?', 'Priority']
for col, header in enumerate(risk_headers, 1):
    ws_risk.cell(row=3, column=col, value=header)
style_header_row(ws_risk, 3, 1, 9)

risk_data = [
    ['Toptica 780nm Laser', 'LOW', 'NO', 'MEDIUM', 'LOW', 'MEDIUM', 'Multi-vendor qualification (Moglabs)', 'YES', 'P2'],
    ['Coherent 480nm Laser', 'LOW', 'NO', 'MEDIUM', 'LOW', 'MEDIUM', 'Toptica DL100 as backup', 'YES', 'P2'],
    ['Rb-85 Vapor Cell (custom)', 'MEDIUM', 'YES', 'MEDIUM', 'LOW', 'HIGH', 'Qualify second supplier (Thorlabs)', 'PARTIAL', 'P1'],
    ['Xilinx ZU47DR RFSoC', 'MEDIUM', 'YES', 'HIGH', 'MEDIUM', 'HIGH', 'Early order, buffer stock, ZU39DR fallback', 'PARTIAL', 'P1'],
    ['Metamaterial Array', 'HIGH', 'YES', 'HIGH', 'LOW', 'CRITICAL', 'In-house fab capability, fractal backup', 'PARTIAL', 'P1'],
    ['CSAC SA.45s', 'LOW', 'YES', 'HIGH', 'LOW', 'MEDIUM', 'Oscilloquartz alternative', 'YES', 'P2'],
    ['White Rabbit (Seven Solutions)', 'LOW', 'NO', 'MEDIUM', 'LOW', 'LOW', 'CERN open-source alternative', 'YES', 'P3'],
    ['GaN PA Module', 'MEDIUM', 'NO', 'HIGH', 'MEDIUM', 'MEDIUM', 'Wolfspeed + Ampleon dual source', 'YES', 'P2'],
    ['NVIDIA Orin AGX', 'LOW', 'YES', 'MEDIUM', 'MEDIUM', 'LOW', 'Orin NX downgrade option', 'YES', 'P3'],
    ['GPU Server (A100)', 'LOW', 'NO', 'MEDIUM', 'LOW', 'LOW', 'Multiple OEMs available', 'YES', 'P3'],
]

row = 5
risk_colors = {'LOW': OK_FILL, 'MEDIUM': CAUTION_FILL, 'HIGH': WARNING_FILL, 'CRITICAL': PatternFill("solid", fgColor="C00000")}

for item in risk_data:
    for col, value in enumerate(item, 1):
        cell = ws_risk.cell(row=row, column=col, value=value)
        if col in [2, 4, 5, 6] and value in risk_colors:
            cell.fill = risk_colors[value]
            if value == 'CRITICAL':
                cell.font = Font(bold=True, color="FFFFFF")
    apply_borders(ws_risk, row, row, 1, 9)
    row += 1

for i, width in enumerate([25, 10, 12, 12, 10, 12, 40, 12, 8], 1):
    ws_risk.column_dimensions[get_column_letter(i)].width = width

# =============================================================================
# SHEET 7: Supplier Directory
# =============================================================================
ws_supp = wb.create_sheet("Suppliers")

ws_supp['A1'] = "QEDMMA Supplier Directory"
ws_supp['A1'].font = Font(bold=True, size=14, color="1F4E79")
ws_supp.merge_cells('A1:H1')

supp_headers = ['Supplier', 'Category', 'Location', 'Contact', 'Payment Terms', 'Min Order', 'Lead Time', 'Notes']
for col, header in enumerate(supp_headers, 1):
    ws_supp.cell(row=3, column=col, value=header)
style_header_row(ws_supp, 3, 1, 8)

suppliers = [
    ['Toptica Photonics', 'Lasers', 'Germany', 'sales@toptica.com', 'Net 30', '€5,000', '12-16 wks', 'Primary laser supplier'],
    ['Coherent', 'Lasers', 'USA/Germany', 'coherent.com', 'Net 30', '€2,000', '8-12 wks', 'OBIS product line'],
    ['Moglabs', 'Lasers (alt)', 'Australia', 'moglabs.com', 'Net 30', 'AUD 5,000', '10-14 wks', 'Alternative laser supplier'],
    ['AMD/Xilinx', 'FPGA', 'USA', 'xilinx.com', 'Net 45', '$10,000', '16-24 wks', 'Direct or Arrow/Mouser'],
    ['Arrow Electronics', 'Distribution', 'Global', 'arrow.com', 'Net 30', '€1,000', '2-20 wks', 'FPGA, passives'],
    ['Mouser Electronics', 'Distribution', 'Global', 'mouser.com', 'Net 30', '€50', '1-20 wks', 'General components'],
    ['DigiKey', 'Distribution', 'Global', 'digikey.com', 'Net 30', '€0', '1-20 wks', 'Fast shipping EU'],
    ['Seven Solutions', 'Timing', 'Spain', 'sevensols.com', 'Net 30', '€3,000', '6-8 wks', 'White Rabbit'],
    ['Microchip', 'Timing', 'USA', 'microchip.com', 'Net 30', '$1,000', '12-16 wks', 'CSAC, clocks'],
    ['NVIDIA', 'AI/GPU', 'USA', 'nvidia.com', 'Net 30', '$5,000', '8-12 wks', 'Jetson, data center'],
    ['Mini-Circuits', 'RF Components', 'USA', 'minicircuits.com', 'Net 30', '$100', '1-4 wks', 'Amplifiers, filters'],
    ['Thorlabs', 'Optics', 'USA/Germany', 'thorlabs.com', 'Net 30', '€100', '1-4 wks', 'General optics'],
    ['Pelican-Hardigg', 'Enclosures', 'USA', 'pelican.com', 'Net 30', '$1,000', '4-6 wks', 'Rugged cases'],
    ['Precision Glassblowing', 'Custom Cells', 'USA', 'precisionglassblowing.com', 'Net 30', '$2,000', '8-10 wks', 'Custom vapor cells'],
]

row = 5
for item in suppliers:
    for col, value in enumerate(item, 1):
        ws_supp.cell(row=row, column=col, value=value)
    apply_borders(ws_supp, row, row, 1, 8)
    row += 1

for i, width in enumerate([22, 15, 12, 25, 12, 12, 12, 30], 1):
    ws_supp.column_dimensions[get_column_letter(i)].width = width

# =============================================================================
# Save Workbook
# =============================================================================
output_path = '/home/claude/qedmma_forge/docs/QEDMMA_BOM_v1.3.xlsx'
wb.save(output_path)
print(f"BOM saved to: {output_path}")
